version: "3.3"
services:
  db:
    image: mysql:9.0.1
    restart: always
    container_name: mysql-avatar-ai
    environment:
      MYSQL_DATABASE: "avatarDB"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3336:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
